version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: docker_project-nginx
    ports:
      - "8080:80"  # Пробрасываем 8080 на 80
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    image: php:8.0-fpm
    container_name: docker_project-php
    volumes:
      - ./code:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
